<?php

/*!
 * https://raccoonsquare.com
 * raccoonsquare@gmail.com
 *
 * Copyright 2012-2021 Demyanchuk Dmitry (raccoonsquare@gmail.com)
 */

if (!defined("APP_SIGNATURE")) {

    header("Location: /");
    exit;
}

$C['ERROR_SUCCESS'] = 0;

$C['ERROR_UNKNOWN'] = 100;
$C['ERROR_ACCESS_TOKEN'] = 101;

$C['ERROR_LOGIN_TAKEN'] = 300;
$C['ERROR_EMAIL_TAKEN'] = 301;
$C['ERROR_FACEBOOK_ID_TAKEN'] = 302;

$C['ERROR_ACCOUNT_ID'] = 400;

$C['DISABLE_LIKES_GCM'] = 0;
$C['ENABLE_LIKES_GCM'] = 1;

$C['DISABLE_COMMENTS_GCM'] = 0;
$C['ENABLE_COMMENTS_GCM'] = 1;

$C['DISABLE_FOLLOWERS_GCM'] = 0;
$C['ENABLE_FOLLOWERS_GCM'] = 1;

$C['DISABLE_MESSAGES_GCM'] = 0;
$C['ENABLE_MESSAGES_GCM'] = 1;

$C['DISABLE_GIFTS_GCM'] = 0;
$C['ENABLE_GIFTS_GCM'] = 1;

$C['SEX_UNKNOWN'] = 0;
$C['SEX_MALE'] = 1;
$C['SEX_FEMALE'] = 2;

$C['USER_CREATED_SUCCESSFULLY'] = 0;
$C['USER_CREATE_FAILED'] = 1;
$C['USER_ALREADY_EXISTED'] = 2;
$C['USER_BLOCKED'] = 3;
$C['USER_NOT_FOUND'] = 4;
$C['USER_LOGIN_SUCCESSFULLY'] = 5;
$C['EMPTY_DATA'] = 6;
$C['ERROR_API_KEY'] = 7;

$C['NOTIFY_TYPE_LIKE'] = 0;
$C['NOTIFY_TYPE_FOLLOWER'] = 1;
$C['NOTIFY_TYPE_MESSAGE'] = 2;
$C['NOTIFY_TYPE_COMMENT'] = 3;
$C['NOTIFY_TYPE_COMMENT_REPLY'] = 4;
$C['NOTIFY_TYPE_FRIEND_REQUEST_ACCEPTED'] = 5;
$C['NOTIFY_TYPE_GIFT'] = 6;

$C['NOTIFY_TYPE_IMAGE_COMMENT'] = 7;
$C['NOTIFY_TYPE_IMAGE_COMMENT_REPLY'] = 8;
$C['NOTIFY_TYPE_IMAGE_LIKE'] = 9;

$C['NOTIFY_TYPE_VIDEO_COMMENT'] = 10;
$C['NOTIFY_TYPE_VIDEO_COMMENT_REPLY'] = 11;
$C['NOTIFY_TYPE_VIDEO_LIKE'] = 12;

$C['NOTIFY_TYPE_REFERRAL'] = 14;

$C['GCM_NOTIFY_CONFIG'] = 0;
$C['GCM_NOTIFY_SYSTEM'] = 1;
$C['GCM_NOTIFY_CUSTOM'] = 2;
$C['GCM_NOTIFY_LIKE'] = 3;
$C['GCM_NOTIFY_ANSWER'] = 4;
$C['GCM_NOTIFY_QUESTION'] = 5;
$C['GCM_NOTIFY_COMMENT'] = 6;
$C['GCM_NOTIFY_FOLLOWER'] = 7;
$C['GCM_NOTIFY_PERSONAL'] = 8;
$C['GCM_NOTIFY_MESSAGE'] = 9;
$C['GCM_NOTIFY_COMMENT_REPLY'] = 10;
$C['GCM_FRIEND_REQUEST_INBOX'] = 11;
$C['GCM_FRIEND_REQUEST_ACCEPTED'] = 12;
$C['GCM_NOTIFY_GIFT'] = 14;
$C['GCM_NOTIFY_SEEN'] = 15;
$C['GCM_NOTIFY_TYPING'] = 16;
$C['GCM_NOTIFY_URL'] = 17;

$C['GCM_NOTIFY_IMAGE_COMMENT_REPLY'] = 18;
$C['GCM_NOTIFY_IMAGE_COMMENT'] = 19;
$C['GCM_NOTIFY_IMAGE_LIKE'] = 20;

$C['GCM_NOTIFY_VIDEO_COMMENT_REPLY'] = 21;
$C['GCM_NOTIFY_VIDEO_COMMENT'] = 22;
$C['GCM_NOTIFY_VIDEO_LIKE'] = 23;

$C['GCM_NOTIFY_REFERRAL'] = 24;

$C['GCM_NOTIFY_MATCH'] = 25;

$C['ACCOUNT_STATE_ENABLED'] = 0;
$C['ACCOUNT_STATE_DISABLED'] = 1;
$C['ACCOUNT_STATE_BLOCKED'] = 2;
$C['ACCOUNT_STATE_DEACTIVATED'] = 3;

$C['ACCOUNT_TYPE_USER'] = 0;
$C['ACCOUNT_TYPE_GROUP'] = 1;
$C['ACCOUNT_TYPE_PAGE'] = 2;

$C['POST_TYPE_DEFAULT'] = 0;
$C['POST_TYPE_PHOTO_UPDATE'] = 1;
$C['POST_TYPE_COVER_UPDATE'] = 2;

$C['PAGE_ANY'] = 0;
$C['PAGE_PROFILE'] = 1;

$C['SECTION_ANY'] = $C['PAGE_ANY'];
$C['SECTION_PROFILE'] = $C['PAGE_PROFILE'];

//

$C['FILE_IMAGE_MAX_UPLOAD_SIZE'] = 3145728;
$C['FILE_VIDEO_MAX_UPLOAD_SIZE'] = 7340035;

$C['BONUS_SIGNUP'] = 10; // bonus for registration in credits
$C['BONUS_REFERRAL'] = 5; // bonus for registration referral in credits
$C['BONUS_OTP_VERIFICATION'] = 100; // bonus for linking mobile phone number

$C['UPGRADES_GHOST_MODE_COST'] = 150;
$C['UPGRADES_VERIFIED_BADGE_COST'] = 100;
$C['UPGRADES_DISABLE_ADS_COST'] = 200;

$C['POST_MAX_IMAGES_COUNT'] = 7;
$C['API_VERSION'] = "v2";

$C['GCM_NOTIFY_PROFILE_PHOTO_APPROVE'] = 1003;
$C['GCM_NOTIFY_PROFILE_PHOTO_REJECT'] = 1004;
$C['GCM_NOTIFY_PROFILE_COVER_APPROVE'] = 1007;
$C['GCM_NOTIFY_PROFILE_COVER_REJECT'] = 1008;

$C['NOTIFY_TYPE_PROFILE_PHOTO_APPROVE'] = 2003;
$C['NOTIFY_TYPE_PROFILE_PHOTO_REJECT'] = 2004;
$C['NOTIFY_TYPE_PROFILE_COVER_APPROVE'] = 2007;
$C['NOTIFY_TYPE_PROFILE_COVER_REJECT'] = 2008;

$C['IMAGE_TYPE_PROFILE_PHOTO'] = 0;
$C['IMAGE_TYPE_PROFILE_COVER'] = 1;

$C['APP_TYPE_ALL'] = -1;
$C['APP_TYPE_MANAGER'] = 0;
$C['APP_TYPE_WEB'] = 1;
$C['APP_TYPE_ANDROID'] = 2;
$C['APP_TYPE_IOS'] = 3;

$C['GALLERY_ITEM_TYPE_IMAGE'] = 0;
$C['GALLERY_ITEM_TYPE_VIDEO'] = 1;

$C['REPORT_TYPE_ITEM'] = 0;
$C['REPORT_TYPE_PROFILE'] = 1;
$C['REPORT_TYPE_MESSAGE'] = 2;
$C['REPORT_TYPE_COMMENT'] = 3;
$C['REPORT_TYPE_GALLERY_ITEM'] = 4;
$C['REPORT_TYPE_MARKET_ITEM'] = 5;
$C['REPORT_TYPE_COMMUNITY'] = 6;

$C['ITEM_TYPE_IMAGE'] = 0;
$C['ITEM_TYPE_VIDEO'] = 1;
$C['ITEM_TYPE_POST'] = 2;
$C['ITEM_TYPE_COMMENT'] = 3;
$C['ITEM_TYPE_GALLERY'] = 4;

// Payments

// PA - PAYMENT ACTION
$C['PA_BUY_CREDITS'] = 0;
$C['PA_BUY_GIFT'] = 1;
$C['PA_BUY_VERIFIED_BADGE'] = 2;
$C['PA_BUY_GHOST_MODE'] = 3;
$C['PA_BUY_DISABLE_ADS'] = 4;
$C['PA_BUY_REGISTRATION_BONUS'] = 5;
$C['PA_BUY_REFERRAL_BONUS'] = 6;
$C['PA_BUY_MANUAL_BONUS'] = 7;
$C['PA_BUY_PRO_MODE'] = 8;
$C['PA_BUY_SPOTLIGHT'] = 9;
$C['PA_BUY_MESSAGE_PACKAGE'] = 10;
$C['PA_BUY_OTP_VERIFICATION'] = 11;

// PT - PAYMENT TYPE
$C['PT_UNKNOWN'] = 0;
$C['PT_CREDITS'] = 1;
$C['PT_CARD'] = 2;
$C['PT_GOOGLE_PURCHASE'] = 3;
$C['PT_APPLE_PURCHASE'] = 4;
$C['PT_ADMOB_REWARDED_ADS'] = 5;
$C['PT_BONUS'] = 6;

$C['CURRENCY_USD'] = 0;
$C['CURRENCY_EUR'] = 1;

// ERROR CODES

$C['ERROR_LOGIN_TAKEN'] = 300;
$C['ERROR_EMAIL_TAKEN'] = 301;
$C['ERROR_FACEBOOK_ID_TAKEN'] = 302;
$C['ERROR_PHONE_TAKEN'] = 303;

$C['ERROR_ACCOUNT_ID'] = 400;

$C['ERROR_FILE_SIZE_BIG'] = 501;
$C['ERROR_FILE_SIZE_SMALL'] = 502;

$C['ERROR_IMAGE_FILE_FORMAT'] = 503;
$C['ERROR_IMAGE_FILE_WIDTH_HEIGHT'] = 504;

$C['ERROR_CLIENT_ID'] = 19100;
$C['ERROR_CLIENT_SECRET'] = 19101;

$C['ERROR_OTP_VERIFICATION'] = 506;
$C['ERROR_OTP_PHONE_NUMBER_TAKEN'] = 507;
$C['ERROR_LIMIT_EXCEEDED'] = 508;

// Signin methods

$C['SIGNIN_EMAIL'] = 0;
$C['SIGNIN_OTP'] = 1;
$C['SIGNIN_FACEBOOK'] = 2;
$C['SIGNIN_GOOGLE'] = 3;
$C['SIGNIN_APPLE'] = 4;
$C['SIGNIN_TWITTER'] = 5;

$C['OAUTH_TYPE_FACEBOOK'] = 0;
$C['OAUTH_TYPE_GOOGLE'] = 1;

// Verification

$C['ENVATO_ITEM_ID'] = 13965025; // My Social Network Android = 13965025

$C['ENVATO_ERROR_PCODE_UNKNOWN'] = 90000;
$C['ENVATO_ERROR_PCODE_INVALID'] = 90001;
$C['ENVATO_ERROR_PCODE_VERIFIED'] = 90002;
$C['ENVATO_ERROR_PCODE_REGISTERED'] = 90003;
$C['ENVATO_ERROR_PCODE_ILLEGAL'] = 90004;